// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploadTracking.DataModel.Model;

namespace UploadTracking.DataModel.Migrations
{
    [DbContext(typeof(UploadTrackingContext))]
    [Migration("20180811223403_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UploadTracking.DataModel.Model.StoreIntegration", b =>
                {
                    b.Property<int>("StoreIntegrationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PlatformTypeId");

                    b.Property<string>("StoreId")
                        .IsUnicode(false);

                    b.Property<string>("StoreName")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("Token")
                        .IsUnicode(false);

                    b.Property<int>("UserId");

                    b.HasKey("StoreIntegrationId");

                    b.HasIndex("UserId");

                    b.ToTable("StoreIntegration");
                });

            modelBuilder.Entity("UploadTracking.DataModel.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("FamilyName");

                    b.Property<string>("FullName");

                    b.Property<string>("GivenName");

                    b.Property<string>("IdToken");

                    b.Property<int>("LoginTypeId");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(250)
                        .IsUnicode(false);

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("UploadTracking.DataModel.Model.StoreIntegration", b =>
                {
                    b.HasOne("UploadTracking.DataModel.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
